export const appConstants = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
  LOGOUT: "USERS_LOGOUT",

  REGISTER_REQUEST: "EMPLOYEE_REGISTER_REQUEST",
  REGISTER_SUCCESS: "EMPLOYEE_REGISTER_SUCCESS",
  REGISTER_FAILURE: "EMPLOYEE_REGISTER_FAILURE",

  FETCH_REQUEST: "DATA_REGISTER_REQUEST",
  FETCH_SUCCESS: "DATA_REGISTER_SUCCESS",
  FETCH_FAILURE: "DATA_REGISTER_FAILURE",

  FETCH_SINGLE_REQUEST: "FETCH_SINGLE_REQUEST",
  FETCH_SINGLE_SUCCESS: "FETCH_SINGLE__SUCCESS",
  FETCH_SINGLE_FAILURE: "FETCH_SINGLE__FAILURE",

  DELETE_REQUEST: "EMPLOYE_DELETE_REQUEST",
  DELETE_SUCCESS: "EMPLOYE_DELETE_SUCCESS",
  DELETE_FAILURE: "EMPLOYE_DELETE_FAILURE",

  FETCH_DEPARTMENT_REQUEST: "FETCH_DEPARTMENT_REQUEST",
  FETCH_DEPARTMENT_SUCCESS: "FETCH_DEPARTMENT_SUCCESS",
  FETCH_DEPARTMENT_FAILURE: "FETCH_DEPARTMENT_FAILURE",
};

export const inventoryConstant = {
  ADD_ITEM: "ADD_ITEM",
  UDATE_ITEM: "UDATE_ITEM",
  GET_ITEMS: "GET_ITEMS",
  ERROR: "ERROR",
  ITEM_REQUEST: "ITEM_REQUEST",
  DELETE_ITEM: "DELETE_ITEM",
};

export const companyConstant = {
  ADD_COMPANY: "ADD_COMPANY",
  GET_COMPANYS: "GET_COMPANYS",
  DELETE_COMPANY: "DELETE_COMPANY",
};

export const errorsConstant = {
  GET_ERRORS: "GET_ERRORS",
};

export const GET_INVOICE = "GET_INVOICE";
export const GET_SIV = "GET_SIV";
export const GET_ORDER = "GET_ORDER";
export const GET_STATUS = "GET_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_SIV = "UPDATE_SIV";

export const itConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  DELETE_REQUEST: "USERS_DELETE_REQUEST",
  DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
  DELETE_FAILURE: "USERS_DELETE_FAILURE",
};
export const salesConstants = {
  ORDER_REQUEST: "ORDER_REQUEST",
  ORDER_SUCCESS: "ORDER__SUCCESS",
  ORDER_FAILURE: "ORDER__FAILURE",

  COMPANY_GETALL_REQUEST: "COMPANY_GETALL_REQUEST",
  COMPANY_GETALL_SUCCESS: "COMPANY_GETALL_SUCCESS",
  COMPANY_GETALL_FAILURE: "COMPANY_GETALL_FAILURE",

  ITEM_GETALL_REQUEST: "ITEM_GETALL_REQUEST",
  ITEM_GETALL_SUCCESS: "ITEM_GETALL_SUCCESS",
  ITEM_GETALL_FAILURE: "ITEM__GETALL_FAILURE",

  DELETE_REQUEST: "USERS_DELETE_REQUEST",
  DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
  DELETE_FAILURE: "USERS_DELETE_FAILURE",
};
