export const appConstants = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
  LOGOUT: "USERS_LOGOUT",

  REGISTER_REQUEST: "DATA_REGISTER_REQUEST",
  REGISTER_SUCCESS: "DATA_REGISTER_SUCCESS",
  REGISTER_FAILURE: "DATA_REGISTER_FAILURE",

  FETCH_REQUEST: "DATA_REGISTER_REQUEST",
  FETCH_SUCCESS: "DATA_REGISTER_SUCCESS",
  FETCH_FAILURE: "DATA_REGISTER_FAILURE",
};

export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  DELETE_REQUEST: "USERS_DELETE_REQUEST",
  DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
  DELETE_FAILURE: "USERS_DELETE_FAILURE",
};

export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
};

export const inventoryConstant = {
  ADD_ITEM: "ADD_ITEM",
  GET_ITEMS: "GET_ITEMS",
  ERROR: "ERROR",
  ITEM_REQUEST: "ITEM_REQUEST",
  DELETE_ITEM: "DELETE_ITEM",
};

export const salesConstant = {
  ADD_ORDER: "ADD_ORDER",
  GET_ORDERS: "GET_ORDERS",
};

export const companyConstant = {
  ADD_COMPANY: "ADD_COMPANY",
  GET_COMPANYS: "GET_COMPANYS",
  DELETE_COMPANY: "DELETE_COMPANY",
};

export const errorsConstant = {
  GET_ERRORS: "GET_ERRORS",
};

export const GET_INVOICE = "GET_INVOICE";
export const GET_SIV = "GET_SIV";
export const GET_ORDER = "GET_ORDER";
